import os

def prepare_pdf_latex(exam_content, output_filename="final_exam.tex"):
    """
    Injects generated exam questions into the master LaTeX template.
    """
    template_path = os.path.join("..", "templates", "knec_template.tex")
    
    with open(template_path, "r") as f:
        template = f.read()
    
    # Replace the placeholder inside the multicols environment
    # We look for a marker in your template or simply append the content
    final_latex = template.replace("% Placeholder for Dynamic Questions Generated by AI", exam_content)
    
    with open(output_filename, "w") as f:
        f.write(final_latex)
        
    return output_filename
