import os

def prepare_pdf_latex(exam_content, output_filename="final_exam.tex"):
    """
    Injects generated exam questions into the master LaTeX template,
    ensuring paths are resolved securely relative to the file location.
    """
    # Use absolute path resolution based on current file location for reliability on Render
    current_dir = os.path.dirname(os.path.abspath(__file__))
    template_path = os.path.abspath(os.path.join(current_dir, "..", "templates", "knec_template.tex"))
    
    # Fallback to current directory path if templates is structured differently
    if not os.path.exists(template_path):
        template_path = os.path.abspath(os.path.join(current_dir, "templates", "knec_template.tex"))

    try:
        if os.path.exists(template_path):
            with open(template_path, "r", encoding="utf-8") as f:
                template = f.read()
        else:
            # Fallback inline template if file cannot be found
            template = r"""
            \documentclass[10pt]{article}
            \usepackage[utf8]{inputenc}
            \usepackage{multicol}
            \begin{document}
            \begin{multicols}{2}
            % Placeholder for Dynamic Questions Generated by AI
            \end{multicols}
            \end{document}
            """
    
    # Replace the placeholder safely
        final_latex = template.replace("% Placeholder for Dynamic Questions Generated by AI", str(exam_content))
    except Exception:
        final_latex = str(exam_content)
    
    # Write to a secure output path
    output_path = os.path.join(current_dir, output_filename)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(final_latex)
        
    return output_path
